/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

//for print f
#include <stdio.h>

#define BLUE_LED_PORT GPIOD
#define BLUE_LED_PIN 15



void delay(void){
	for(uint32_t i = 0; i < 500000/2; i ++);
}



int main(void)
{
	printf("System booted with Default clock\n");
	delay();

	//Turn on Blue LED with pure CMSIS
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;

	GPIOD->MODER |= GPIO_MODER_MODER15_0;
	GPIOD->MODER &= ~GPIO_MODER_MODER15_1;
	GPIOD->OTYPER &= ~GPIO_OTYPER_OT_15;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR15_0;
	GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR15_1;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR15_0;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR15_1;

	delay();

	printf("GPIO D setup and now will turn on blue LED \n");


	GPIOD->BSRR |= GPIO_BSRR_BS_15;

	printf("Blue LED is now ON\n");

	delay();
	delay();
	delay();

	printf("GPIO D setup will turn off blue LED\n");

	GPIOD->BSRR |= GPIO_BSRR_BR_15;

	printf("Blue LED is now OFF\n");








    /* Loop forever */
	for(;;);
}
