/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *L
 ******************************************************************************
 */


#include <stdint.h>
#include "stm32f4xx.h"



void _init() {
	//dummy
}


void init_indicators(); 



int main(void)
{
	init_indicators();
	
    /* Loop forever */
	for(;;);
}


void init_indicators() 
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;

	//BLUE
	GPIOD->MODER |= GPIO_MODER_MODER15_0;
	GPIOD->MODER &= ~GPIO_MODER_MODER15_1;
	GPIOD->OTYPER &= ~GPIO_OTYPER_OT_15;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR15_0;
	GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR15_1;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR15_0;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR15_1;


	//RED
	GPIOD->MODER |= GPIO_MODER_MODER14_0;
	GPIOD->MODER &= ~GPIO_MODER_MODER14_1;
	GPIOD->OTYPER &= ~GPIO_OTYPER_OT_14;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR14_0;
	GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR14_1;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR14_0;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR14_1;

	//ORANGE
	GPIOD->MODER |= GPIO_MODER_MODER13_0;
	GPIOD->MODER &= ~GPIO_MODER_MODER13_1;
	GPIOD->OTYPER &= ~GPIO_OTYPER_OT_13;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR13_0;
	GPIOD->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR13_1;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR13_0;
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR13_1;


}

